# Generated by Django 6.0.4 on 2026-05-24 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_address_account_card_account_userprofile'),
        ('tracking', '0004_alter_track_tracking_number_trackingevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Billing',
        ),
    ]
