# Generated by Django 6.0.4 on 2026-06-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_address_user_remove_billing_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
