# Generated by Django 6.0.4 on 2026-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_address_is_default_billing_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='home', max_length=10),
        ),
    ]
