# Generated by Django 6.0.4 on 2026-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_category_description_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('sofa', 'Sofa'), ('armchair', 'Armchair'), ('dining_table', 'Dining Table'), ('coffee_table', 'Coffee Table'), ('bed', 'Bed'), ('dresser', 'Dresser'), ('wardrobe', 'Wardrobe'), ('desk', 'Desk'), ('bookshelf', 'Bookshelf'), ('tv_stand', 'TV Stand'), ('nightstand', 'Nightstand'), ('recliner', 'Recliner'), ('bench', 'Bench'), ('bar_stool', 'Bar Stool'), ('ottoman', 'Ottoman')], max_length=100),
        ),
    ]
