# Generated by Django 6.0.4 on 2026-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='design_images/'),
            preserve_default=False,
        ),
    ]
