# Generated by Django 6.0.4 on 2026-04-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
    ]
