# Generated by Django 6.0.4 on 2026-04-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_item_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='value',
            new_name='discount_price',
        ),
    ]
