# Generated by Django 6.0.4 on 2026-04-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_itemimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimages',
            options={'ordering': ['item', 'order'], 'verbose_name_plural': 'Item Images'},
        ),
        migrations.AddField(
            model_name='itemimages',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
