# Generated by Django 6.0.4 on 2026-04-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_itemimages_options_itemimages_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimages',
            old_name='image',
            new_name='images',
        ),
    ]
