# Generated by Django 6.0.4 on 2026-04-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_rename_image_itemimages_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimages',
            options={'ordering': ['order'], 'verbose_name_plural': 'Item Images'},
        ),
        migrations.RenameField(
            model_name='itemimages',
            old_name='images',
            new_name='image',
        ),
    ]
