# Generated by Django 6.0.4 on 2026-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_itemimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
