# Generated by Django 6.0.4 on 2026-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
