# Generated by Django 6.0.4 on 2026-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_item_purchase_count_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
