# Generated by Django 6.0.4 on 2026-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_item_rating_item_rating_count_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
