# Generated by Django 6.0.4 on 2026-05-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
        migrations.DeleteModel(
            name='SignOut',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
