# Generated by Django 6.0.4 on 2026-05-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tracking', '0002_track_address_track_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order'),
            preserve_default=False,
        ),
    ]
