# Generated by Django 6.0.4 on 2026-05-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_track_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='tracking_number',
            field=models.CharField(blank=True, default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.track')),
            ],
            options={
                'indexes': [models.Index(fields=['track'], name='tracking_tr_track_i_76ed38_idx'), models.Index(fields=['status'], name='tracking_tr_status_780455_idx')],
            },
        ),
    ]
